#!/usr/bin/env python3
"""Append 86 missing atoms to schema.yaml."""
import yaml, os

SCHEMA = os.path.join(os.path.dirname(__file__), '..', 'atoms', 'schema.yaml')

SOURCE = {
    'name': 'a2ui-catalogue',
    'url': 'https://github.com/curtiskrygier/a2ui-catalogue',
    'license': 'MIT',
}
ASW = ['google-apps-script-web']

def atom(type_, desc, compact, fields):
    return {
        'type': type_,
        'description': desc,
        'compact_description': compact,
        'surfaces': {'works_on': ASW},
        'fields': fields,
        'source': SOURCE,
    }

NEW_ATOMS = [
    # ── Core primitives ────────────────────────────────────────────────────────
    atom('paragraph', 'Prose paragraph block (alias for body, google-apps-script-web only)',
         'prose paragraph (GAS alias for body)',
         {'text': 'string'}),
    atom('text_block', 'Plain text block rendered as a paragraph',
         'plain text block',
         {'text': 'string'}),
    atom('blockquote', 'Styled pull-quote with optional attribution line',
         'styled pull-quote with attribution',
         {'text': 'string', 'attribution': 'string (optional)'}),
    atom('spacer', 'Vertical whitespace gap between atoms',
         'vertical whitespace gap',
         {'height': 'string or number (optional, CSS height e.g. 24 or "2rem")'}),
    atom('tag_chip', 'Small inline tag/label chip',
         'inline tag chip',
         {'text': 'string', 'color': 'string (optional, hex colour)'}),
    atom('badge', 'Inline badge pill with accent colour',
         'inline badge pill',
         {'text': 'string', 'color': 'string (optional, hex colour)'}),
    atom('inline_code', 'Monospace inline code span',
         'monospace inline code span',
         {'text': 'string'}),
    atom('code_block', 'Syntax-highlighted code block',
         'syntax-highlighted code block',
         {'language': 'string (optional, e.g. python, js, yaml)', 'content': 'string'}),
    atom('link_button', 'Text hyperlink styled as a button',
         'text hyperlink button',
         {'url': 'string', 'label': 'string'}),
    atom('cta_button', 'Full-width call-to-action button linking to a URL',
         'call-to-action button',
         {'url': 'string', 'label': 'string', 'color': 'string (optional, hex)'}),
    atom('nav_link', 'Navigation link, opens in top frame',
         'navigation link',
         {'url': 'string', 'label': 'string'}),
    atom('info_card', 'Simple card with title and body text',
         'simple info card with title and body',
         {'title': 'string', 'text': 'string'}),

    # ── AI atoms ───────────────────────────────────────────────────────────────
    atom('ai_build_trace', 'Token usage and model trace card — shows Gemini call stats inline on a page',
         'Gemini token usage trace card',
         {
             'model': 'string (optional, e.g. gemini-2.5-flash)',
             'prompt_tokens': 'integer (optional)',
             'thinking_tokens': 'integer (optional)',
             'output_tokens': 'integer (optional)',
             'total_tokens': 'integer (optional)',
         }),
    atom('gemini_prompt', 'Inline Gemini prompt input that calls the GAS callGemini() function from within a rendered page',
         'inline Gemini prompt input widget',
         {
             'label': 'string (optional)',
             'placeholder': 'string (optional)',
             'accent': 'string (optional, hex colour)',
         }),

    # ── Dark-theme atoms ────────────────────────────────────────────────────────
    atom('dark_hero', 'Full-width dark hero banner with gradient background, badge, headline, and CTA button',
         'dark hero banner with gradient and CTA',
         {
             'heading': 'string',
             'subtext': 'string (optional)',
             'badge': 'string (optional, small label above heading)',
             'gradient': 'string (optional, CSS gradient e.g. linear-gradient(135deg,#1e1b4b,#312e81))',
             'cta_label': 'string (optional)',
             'cta_url': 'string (optional)',
             'align': 'string (optional, left|center)',
         }),
    atom('glowing_stat', 'Single large stat with neon glow effect on dark background',
         'neon-glow stat number on dark card',
         {
             'value': 'string or number',
             'label': 'string (optional)',
             'colour': 'string (optional, hex, default #22d3ee)',
             'size': 'string (optional, CSS font-size)',
             'prefix': 'string (optional)',
             'suffix': 'string (optional)',
             'glow': 'boolean (optional)',
         }),
    atom('glass_card', 'Frosted-glass card on a gradient background — ideal for dark theme pages',
         'frosted-glass card on gradient background',
         {
             'title': 'string (optional)',
             'text': 'string (optional, supports markdown)',
             'bg': 'string (optional, CSS gradient or colour for the outer container)',
         }),
    atom('gradient_border_card', 'Card with an animated gradient border stroke on dark background',
         'animated gradient border card',
         {
             'title': 'string (optional)',
             'content': 'string (optional)',
             'colours': 'array of hex strings (optional, gradient stops)',
             'bg': 'string (optional, card background)',
             'angle': 'number (optional, gradient angle degrees)',
             'padding': 'string (optional)',
             'radius': 'string (optional)',
         }),
    atom('floating_orbs', 'Decorative blurred colour orbs that float in a dark background area',
         'decorative blurred colour orbs background',
         {
             'orbs': 'array of {colour, size, x, y} (optional)',
             'blur': 'number (optional, blur px)',
             'opacity': 'number (optional, 0–1)',
             'animate': 'boolean (optional)',
         }),
    atom('neon_text', 'Neon-coloured glowing text, ideal for dark technical pages',
         'neon-glow coloured text',
         {
             'text': 'string',
             'colour': 'string (optional, hex, default #22d3ee)',
             'size': 'string (optional, CSS font-size)',
             'weight': 'string or number (optional)',
             'align': 'string (optional, left|center|right)',
             'flicker': 'boolean (optional)',
         }),
    atom('dark_feature_grid', 'Responsive feature grid on dark background — icon, title, description per cell',
         'dark-theme feature grid with icons',
         {
             'features': 'array of {icon, title, description, colour}',
             'columns': 'integer (optional, default 3)',
             'accent': 'string (optional, hex)',
         }),
    atom('dark_divider', 'Thin horizontal rule for dark theme pages',
         'dark-theme horizontal divider',
         {
             'colour': 'string (optional, hex)',
             'margin': 'string (optional, CSS margin)',
             'height': 'string (optional, CSS height)',
         }),

    # ── Alias atoms (charts.gs) ─────────────────────────────────────────────────
    atom('ambient_gradient', 'Full-screen animated aurora background — alias for aurora_background',
         'animated aurora/ambient gradient background',
         {
             'title': 'string (optional)',
             'text': 'string (optional)',
         }),
    atom('depth_stack', 'Stacked layered cards with parallax depth — alias for card_stack',
         'stacked cards with depth parallax',
         {
             'cards': 'array of {title, text} (alias: items)',
             'count': 'integer (optional, max cards to show)',
         }),
    atom('scramble_reveal', 'Text that decrypts/un-scrambles character-by-character on scroll — alias for encrypted_reveal',
         'character-scramble text reveal on scroll',
         {
             'text': 'string (alias: content, label)',
             'title': 'string (optional)',
         }),
    atom('scroll_trigger', 'Content that animates in from a direction when scrolled into view — alias for reveal_on_scroll',
         'scroll-triggered animated reveal',
         {
             'text': 'string (alias: content)',
             'title': 'string (optional)',
             'delay': 'number (optional, seconds)',
             'direction': 'string (optional, up|down|left|right)',
         }),
    atom('flow_connector', 'Animated dashed beam connecting two labelled nodes — alias for animated_beam',
         'animated beam connector between two nodes',
         {
             'from': 'string',
             'to': 'string',
             'label': 'string (optional)',
             'color': 'string (optional, hex)',
         }),
    atom('live_metric', 'Animated counter that counts up from start to a target value — alias for animated_counter',
         'animated counting number (alias for animated_counter)',
         {
             'value': 'number (alias: end)',
             'start': 'number (optional)',
             'duration': 'number (optional, seconds)',
             'prefix': 'string (optional)',
             'suffix': 'string (optional)',
             'label': 'string (optional)',
             'decimals': 'integer (optional)',
         }),
    atom('deadline_ticker', 'Countdown timer showing days/hours/minutes/seconds to a target date — alias for countdown_timer',
         'countdown timer to a target date (alias)',
         {
             'target_date': 'string (ISO date, alias: target)',
             'label': 'string (optional, alias: title)',
         }),
    atom('pattern_background', 'Dot-grid repeating pattern background — alias for dot_grid_background',
         'dot-grid pattern background (alias)',
         {
             'color': 'string (optional, dot colour hex)',
             'bg': 'string (optional, background colour)',
             'size': 'number (optional, dot spacing px)',
             'title': 'string (optional)',
             'text': 'string (optional)',
         }),

    # ── Charts standalone atoms ─────────────────────────────────────────────────
    atom('glitch_text', 'Cyan glitch-effect headline — periodic RGB-split animation',
         'RGB-split glitch-effect headline',
         {
             'text': 'string (alias: title, label)',
             'size': 'string (optional, CSS font-size, default 2rem)',
         }),
    atom('neon_glow', 'Pulsing neon-glow text on a near-black background',
         'pulsing neon-glow text on dark card',
         {
             'text': 'string (alias: title, label)',
             'color': 'string (optional, hex, default #22d3ee)',
             'size': 'string (optional, CSS font-size)',
         }),
    atom('magnetic_button', 'Button that follows the cursor magnetically on hover',
         'magnetic cursor-following button',
         {
             'text': 'string (alias: label, title)',
             'color': 'string (optional, hex background)',
         }),
    atom('confetti_burst', 'Auto-firing confetti animation over a dark achievement card',
         'auto-fire confetti achievement card',
         {
             'label': 'string (alias: text, title, default "Achievement Unlocked!")',
         }),
    atom('confetti_trigger', 'Button that triggers confetti explosion when clicked',
         'click-to-trigger confetti button',
         {
             'label': 'string (message shown after click, alias: text)',
             'trigger': 'string (button label, alias: button)',
         }),
    atom('floating_particles', 'Floating particle field background (canvas fallback placeholder)',
         'floating particles background (canvas placeholder)',
         {
             'title': 'string (optional, alias: label, text)',
         }),
    atom('parallax_section', 'Parallax scroll section (canvas fallback placeholder)',
         'parallax scroll section (canvas placeholder)',
         {
             'title': 'string (optional, alias: label, text)',
         }),
    atom('scroll_progress', 'Thin fixed progress bar at the top of the viewport showing scroll position',
         'fixed scroll-progress bar at page top',
         {
             'color': 'string (optional, hex, default #6366f1)',
             'height': 'number (optional, px, default 3)',
         }),
    atom('live_clock', 'Live ticking clock on a dark card, updates every second',
         'live ticking clock widget',
         {
             'label': 'string (optional, alias: title)',
             'format': 'string (optional, 12h|24h, default 24h)',
             'timezone': 'string (optional, IANA tz label for display only)',
         }),
    atom('decision_tree', 'Interactive collapsible decision tree with nested branches',
         'interactive collapsible decision tree',
         {
             'nodes': 'array of {text, children: [{text, children}]} — nested tree nodes',
             'title': 'string (optional)',
         }),
    atom('step_reveal_sequence', 'Tab-style step-by-step content with radio-button navigation',
         'tabbed step-by-step sequence',
         {
             'steps': 'array of {title, text} — each step shown in its own tab panel',
         }),
    atom('chat_sequence', 'Animated conversation thread with user/assistant bubbles',
         'animated chat conversation thread',
         {
             'messages': 'array of {role (user|assistant), name (optional), text}',
         }),
    atom('tooltip_glossary', 'Glossary list where hovering a term shows its definition as a tooltip',
         'glossary with hover tooltips',
         {
             'terms': 'array of {term, definition}',
             'text': 'string (optional, introductory prose, alias: intro)',
         }),
    atom('focus_lens', 'Blurred background with a clear focused panel in the centre — spotlight effect',
         'spotlight focus lens on blurred background',
         {
             'title': 'string (optional)',
             'text': 'string (optional, alias: content)',
         }),
    atom('terminal_boot', 'Dark terminal window that types out boot/log lines one by one',
         'animated terminal boot sequence',
         {
             'lines': 'array of strings — lines typed out in sequence',
             'title': 'string (optional, shown as terminal header)',
             'speed': 'number (optional, ms between lines, default 380)',
         }),
    atom('stagger_list', 'List of items that animate in with a staggered delay — supports icons and descriptions',
         'stagger-animated list of items',
         {
             'items': 'array of strings or {icon, text, sub} objects',
             'direction': 'string (optional, up|down|left|right)',
             'stagger': 'number (optional, delay between items in seconds, default 0.1)',
         }),
    atom('liquid_button', 'Button that morphs between circular and rounded-rectangle on hover',
         'liquid morphing hover button',
         {
             'text': 'string (alias: label, title)',
             'color': 'string (optional, hex background)',
         }),
    atom('highlight_sweep', 'Text with an animated highlight sweep underline that plays on load',
         'animated highlight sweep text',
         {
             'text': 'string (alias: content)',
             'color': 'string (optional, highlight colour hex, default #fef08a yellow)',
             'delay': 'number (optional, seconds before sweep starts)',
             'size': 'string (optional, CSS font-size)',
         }),
    atom('progress_reveal', 'Animated progress bar that counts from 0 to a value when scrolled into view',
         'scroll-triggered animated progress bar',
         {
             'value': 'number (0–100, alias: percent)',
             'label': 'string (optional, alias: title)',
             'color': 'string (optional, hex)',
             'suffix': 'string (optional, default %)',
             'height': 'number (optional, bar height px)',
         }),
    atom('big_reveal', 'Large centred number or word that pops in with a spring scale animation',
         'spring-animation big number or word reveal',
         {
             'text': 'string (the big value, alias: value, label)',
             'sub': 'string (optional subtitle below, alias: subtitle)',
             'color': 'string (optional, hex)',
             'size': 'string (optional, CSS font-size, default 5rem)',
             'delay': 'number (optional, seconds)',
         }),
    atom('kinetic_headline', 'Headline where each word flies in with a staggered animation',
         'word-by-word kinetic headline animation',
         {
             'text': 'string (alias: title)',
             'size': 'string (optional, CSS font-size)',
             'color': 'string (optional, hex)',
             'stagger': 'number (optional, seconds between words)',
             'style': 'string (optional, up|down|scale|fade)',
         }),
    atom('text_reveal_mask', 'Headline that sweeps in from left using clip-path mask animation',
         'clip-path text reveal mask animation',
         {
             'text': 'string (alias: title)',
             'size': 'string (optional, CSS font-size)',
             'color': 'string (optional, hex)',
             'delay': 'number (optional, seconds)',
         }),
    atom('split_reveal', 'Content hidden behind two coloured panels that slide apart to reveal it',
         'split-panel reveal animation',
         {
             'title': 'string (optional)',
             'text': 'string (optional, alias: content)',
             'color': 'string (optional, panel colour hex)',
             'delay': 'number (optional, seconds)',
         }),
    atom('mesh_gradient', 'Dark card with radial mesh/blob gradient background — vivid multi-colour',
         'dark card with radial mesh gradient background',
         {
             'title': 'string (optional)',
             'text': 'string (optional, alias: content)',
             'bg': 'string (optional, base background colour)',
             'colors': 'array of hex strings (optional, gradient blob colours)',
         }),
    atom('stripe_background', 'Card with animated diagonal stripe background pattern',
         'animated diagonal stripe background card',
         {
             'title': 'string (optional)',
             'text': 'string (optional, alias: content)',
             'color1': 'string (optional, hex, first stripe colour)',
             'color2': 'string (optional, hex, second stripe colour)',
             'speed': 'number (optional, animation seconds)',
         }),
    atom('status_timeline', 'Vertical timeline with status dots (done/active/pending/error/warning)',
         'status-dot vertical timeline',
         {
             'events': 'array of {title, date (optional), text (optional), status (done|active|pending|error|warning)}',
             'title': 'string (optional)',
         }),
    atom('counter_group', 'Row of animated counting stats separated by dividers',
         'row of animated stat counters',
         {
             'stats': 'array of {value, label, color (optional), prefix (optional), suffix (optional), decimals (optional)} (alias: items)',
         }),
    atom('orbit_diagram', 'Animated orbiting node diagram — central node with satellite labels on a dashed orbit ring',
         'animated orbit diagram with satellite nodes',
         {
             'center': 'string (label for the central node)',
             'nodes': 'array of strings or {label, color} objects',
             'color': 'string (optional, hex accent)',
             'speed': 'number (optional, animation speed)',
         }),
    atom('noise_card', 'Dark card with subtle SVG film-grain noise texture overlay',
         'dark card with film-grain noise texture',
         {
             'title': 'string (optional)',
             'text': 'string (optional, alias: content)',
             'bg': 'string (optional, background colour)',
             'color': 'string (optional, text colour)',
         }),
    atom('comparison_morph', 'Draggable before/after slider revealing two text panels side by side',
         'draggable before/after comparison slider',
         {
             'before': '{label (optional), text}',
             'after': '{label (optional), text}',
             'title': 'string (optional)',
         }),
    atom('word_cloud', 'Interactive word cloud — static words or live Google Sheets feed with submit input',
         'interactive word cloud with optional live Sheet feed',
         {
             'words': 'array of {text, weight} (optional static words)',
             'palette': 'array of hex strings (optional, word colours)',
             'placeholder': 'string (optional, input placeholder)',
             'accent': 'string (optional, hex accent for input bar)',
             'sheet_url': 'string (optional, Google Sheet CSV URL for live words)',
             'write_url': 'string (optional, GAS doGet URL to write submissions)',
             'poll': 'number (optional, poll interval seconds)',
         }),
    atom('quiz_set', 'Multi-question quiz with multiple-choice options, per-question explanations, pass score, and result screen',
         'multi-question interactive quiz',
         {
             'title': 'string (optional)',
             'questions': 'array of {question, options: [string], correct: integer (0-based index), explanation (optional)}',
             'pass_score': 'integer (optional, % to pass, default 70)',
             'accent': 'string (optional, hex)',
             'on_pass': 'object (optional, atom block shown on pass)',
             'on_fail': 'object (optional, atom block shown on fail)',
         }),

    # ── Effects ─────────────────────────────────────────────────────────────────
    atom('cursor_glow', 'Smooth radial glow that follows the mouse cursor around the page',
         'mouse-following radial cursor glow',
         {
             'color': 'string (optional, hex, default #6366f1)',
             'size': 'number (optional, glow diameter px, default 280)',
             'blur': 'number (optional, blur px, default 80)',
             'opacity': 'number (optional, 0–1, default 0.18)',
         }),

    # ── Canvas atoms ────────────────────────────────────────────────────────────
    atom('globe_3d', 'Spinning interactive 3-D wireframe or earth globe rendered on HTML5 canvas — draggable with inertia',
         'interactive spinning 3-D globe (wire or earth)',
         {
             'size': 'number (optional, diameter px, default 300)',
             'color': 'string (optional, hex accent, default #6366f1)',
             'speed': 'number (optional, auto-spin speed, default 0.006)',
             'lines': 'number (optional, latitude line count, default 10)',
             'theme': 'string (optional, wire|earth, default wire)',
             'dots': 'array of {lat, lon, label (optional), color (optional)} (optional, pins on globe)',
             'arcs': 'array of {from: [lat,lon], to: [lat,lon], color (optional)} (optional, great-circle arcs)',
         }),
    atom('geo_mercator_radar', 'Interactive Mercator projection map with draggable pan, node pins, and animated link vectors — dark radar aesthetic',
         'dark-theme interactive Mercator map with node pins and links',
         {
             'title': 'string (optional)',
             'color': 'string (optional, hex accent, default #00f2ff)',
             'height': 'number (optional, px, default 450)',
             'nodes': 'array of {id, name, lat, lon, value (optional)}',
             'links': 'array of {from: id, to: id} (optional)',
         }),
    atom('geo_contour_waves', 'Animated isobaric atmospheric contour wave field — fluid procedural sine/cosine curves on dark background',
         'animated atmospheric contour wave field',
         {
             'title': 'string (optional)',
             'color': 'string (optional, hex, default #a78bfa)',
             'intensity': 'number (optional, wave band count, default 4, max 8)',
             'height': 'number (optional, px, default 350)',
         }),
    atom('multi_surface', 'One data pool rendered simultaneously across three surface engines: spatial map (desktop), phone frame card list (mobile), circular focus face (IoT/watch)',
         'three-engine multi-surface demo atom',
         {
             'title': 'string (optional)',
             'nodes': 'array of {id, type, label, temp (optional), value (optional), intensity (0–100, optional), coords: {x, y}}',
         }),
    atom('geo_europe_airspace', 'Interactive SVG European airspace map — country outlines, airport pins, simulated flight tracks, click-to-open TMA playbook',
         'interactive European airspace map with airports and flights',
         {
             'title': 'string (optional)',
             'focus': 'string (optional, country name to highlight, alias: country)',
             'sim_flights': 'array of {callsign, from: [lat,lon], to: [lat,lon]} (optional simulated flight tracks)',
             'airports': 'boolean (optional, show airport pins, default true)',
         }),

    # ── Data atoms ─────────────────────────────────────────────────────────────
    atom('feed_status', 'Live-feed status pill — shows LIVE (n) or SIM based on data published to a named feed',
         'live/sim status pill for a named data feed',
         {
             'name': 'string (feed name to subscribe to)',
             'label': 'string (optional, text prefix in pill)',
             'size': 'string (optional, CSS font-size, default 0.6rem)',
         }),

    # ── Playbook ────────────────────────────────────────────────────────────────
    atom('playbook', 'Full-screen multi-slide presentation deck — each slide is its own atom block array, with shared data feeds and slide navigation',
         'multi-slide fullscreen presentation playbook',
         {
             'slides': 'array of {id (optional), blocks: [atom block objects]} — each slide is a full block list',
             'shared_blocks': 'array of atom block objects (optional, data feeds etc. rendered once)',
             'transition': 'string (optional, fade|slide, default fade)',
         }),

    # ── Demo kit ────────────────────────────────────────────────────────────────
    atom('surface_unlocked', 'Game-style "NEW SURFACE UNLOCKED" achievement notification card',
         'achievement-style surface unlocked notification',
         {
             'icon': 'string (optional, emoji, default ⚡)',
             'surface': 'string (surface/feature name displayed large)',
             'sub': 'string (optional, subtitle, default NEW SURFACE UNLOCKED)',
             'accent': 'string (optional, hex)',
         }),
    atom('schema_reveal', 'Decodes the current page ?p= URL and displays the JSON schema that built this page',
         'self-reveal: shows this page\'s own JSON schema',
         {
             'title': 'string (optional)',
             'accent': 'string (optional, hex)',
         }),
    atom('url_anatomy', 'Visually annotates the current renderer URL, highlighting the GAS endpoint, ?p= parameter, and encoded payload',
         'annotated URL anatomy diagram',
         {
             'accent': 'string (optional, hex)',
         }),
    atom('schema_qr', 'QR code for the current page URL (or a fixed URL) via Google Charts API',
         'QR code for current or given URL',
         {
             'url': 'string (optional, fixed URL — defaults to current page URL)',
             'label': 'string (optional)',
             'sub': 'string (optional, sub-label below QR)',
             'size': 'number (optional, px, default 220)',
         }),
    atom('take_away_card', 'Bold single-insight pull-quote card designed to be screenshotted',
         'bold screenshot-ready insight card',
         {
             'headline': 'string (alias: text, quote, insight)',
             'sub': 'string (optional, attribution/source, alias: author, source)',
             'accent': 'string (optional, hex)',
             'size': 'string (optional, CSS font-size)',
             'gradient': 'array of 2 hex strings (optional, background gradient colours)',
         }),
    atom('next_step_strip', 'Horizontal strip of numbered next steps with optional links',
         'horizontal numbered next-steps strip',
         {
             'steps': 'array of {number (optional), label, detail (optional, alias: action), url (optional)}',
             'accent': 'string (optional, hex)',
         }),
    atom('copy_prompt', 'Monospace copyable text block — ideal for sharing Gemini prompts or code',
         'copyable monospace prompt/code block',
         {
             'prompt': 'string (text to display and copy, alias: text, content)',
             'label': 'string (optional, header label)',
             'accent': 'string (optional, hex)',
         }),
    atom('atom_anatomy', 'Side-by-side panel showing a rendered atom alongside its raw JSON schema',
         'rendered atom + raw schema side-by-side anatomy view',
         {
             'label': 'string (optional, panel header)',
             'schema': 'object (atom block JSON to render and display)',
             'accent': 'string (optional, hex)',
         }),
    atom('renderer_stats', 'Simple stat grid showing custom key/value pairs — used to show renderer capabilities',
         'stat grid for renderer capability metrics',
         {
             'stats': 'array of {value, label}',
             'sub': 'string (optional, footer note)',
             'accent': 'string (optional, hex)',
         }),
    atom('prompt_to_schema', 'Three-panel flow diagram: natural language prompt → generated JSON schema → rendered page',
         'three-panel prompt → schema → output flow',
         {
             'prompt': 'string (the input prompt text)',
             'schema': 'object or string (the generated JSON schema)',
             'output': 'string (description of the rendered output)',
             'labels': 'array of 3 strings (optional, panel headers)',
             'accent': 'string (optional, hex)',
         }),
    atom('before_after_stack', 'Animated comparison: old approach items cross out one by one, then new approach slides in',
         'old-vs-new stack comparison animation',
         {
             'items': 'array of strings (old approach items to cross out, alias: before_items)',
             'before_label': 'string (optional)',
             'after_label': 'string (optional)',
             'result': 'string (the new approach shown after animation, alias: after_text)',
             'delay': 'number (optional, seconds between strikes)',
             'accent': 'string (optional, hex)',
         }),
    atom('live_vote', 'Live audience voting: buttons to vote, bar chart results, optional Google Sheets backend',
         'live audience voting with real-time bar chart results',
         {
             'question': 'string',
             'options': 'array of strings (vote choices)',
             'sheet_url': 'string (optional, Google Sheet CSV for live tallies)',
             'write_url': 'string (optional, GAS doGet URL to record votes)',
             'poll': 'number (optional, poll interval ms, default 5000)',
             'accent': 'string (optional, hex)',
         }),
    atom('reaction_shower', 'Emoji reaction buttons — tapping rains the emoji down the screen, with optional Sheet-backed totals',
         'emoji reaction buttons with raining particles',
         {
             'reactions': 'array of emoji strings (optional, default 🔥💡🤯👏)',
             'write_url': 'string (optional, GAS doGet URL to record reactions)',
             'sheet_url': 'string (optional, Google Sheet CSV for live counts)',
             'poll': 'number (optional, poll interval ms)',
             'accent': 'string (optional, hex)',
         }),
    atom('raise_hand', 'Audience raise-hand button with live count — optional Google Sheets backend',
         'raise-hand button with live participant count',
         {
             'question': 'string (optional, prompt text above button)',
             'label': 'string (optional, button label, default ✋ Raise hand)',
             'write_url': 'string (optional, GAS doGet URL to record hands)',
             'sheet_url': 'string (optional, Google Sheet CSV for live count)',
             'poll': 'number (optional, poll interval ms)',
             'accent': 'string (optional, hex)',
         }),
    atom('surface_map', 'Visual diagram showing the A2UI surfaces — schema feeds into each render target',
         'A2UI surface diagram (schema → surfaces)',
         {
             'title': 'string (optional)',
             'surfaces': 'array of {name, icon, desc, color} (optional, defaults to GAS/Meet/Sites/Chat)',
             'accent': 'string (optional, hex)',
         }),
    atom('speed_counter', 'Stopwatch that starts ticking on load and freezes when the page finishes loading — shows real page load time',
         'live page-load stopwatch',
         {
             'label': 'string (optional, e.g. "Page loaded in")',
             'sub': 'string (optional, sub-label)',
             'accent': 'string (optional, hex)',
         }),
    atom('live_edit', 'Embedded mini schema editor with a textarea for typing a single atom JSON block and a live rendered preview below',
         'embedded live atom JSON editor with preview',
         {
             'placeholder': 'string (optional, example atom JSON)',
             'accent': 'string (optional, hex)',
             'renderer_url': 'string (optional, renderer base URL for linking)',
         }),
]

with open(SCHEMA) as f:
    data = yaml.safe_load(f)

existing_types = {b['type'] for b in data['blocks']}
added = 0
for a in NEW_ATOMS:
    if a['type'] not in existing_types:
        data['blocks'].append(a)
        added += 1
    else:
        print(f'  skip (exists): {a["type"]}')

with open(SCHEMA, 'w') as f:
    yaml.dump(data, f, allow_unicode=True, sort_keys=False, default_flow_style=False, width=120)

print(f'\n✓ Added {added} atoms. Total blocks: {len(data["blocks"])}')
